### ISSUE TITLE
在已经登陆微信的情况下提示未登陆

### ISSUE THREAD

**Issue by YaoGGGG** [HenryXiaoYang/XYBot#16]
<img width="471" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/2baecbf4-4759-4541-958d-39540f4409b6">
感谢大佬！
在自己安装过程中和配置不一样的地方：
之前pip3 -r requirements.txt的时候报错，最终运行的pip3 install -r requirements.txt
start.py之后有几个包提示import不成功，手动安装的
然后就导致了登陆不成功的效果，求解应该怎么排障，手动卸载重装下依赖的包？🙏

**Comment by HenryXiaoYang** [comment]
首先检查是否能连接到pypi官方源，如果服务器在国内可以换成国内镜像源。然后重装依赖包 ```pip3 install --upgrade -r requirements.txt```

**Comment by YaoGGGG** [comment]
unset 了 一下，这个应该算连上官方源了吧。
<img width="325" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/8ca125ce-a6e8-4422-a048-4e738e4c9b6c">
然后升级时候有已安装的报错，我就忽略重新升级了
<img width="305" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/79234710-6032-4495-b08e-70ce74c614b3">
最后还是这样
<img width="401" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/ddee2026-d317-4373-9a5e-b2d93f859de0">
感恩！感谢！

**Comment by HenryXiaoYang** [comment]
查看一下docker日志，微信hook是否注入成功

**Comment by YaoGGGG** [comment]
没有……我现在怀疑我是Windows电脑，所以一开始启动docker那个语句转来转去写错了？
<img width="638" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/55776385-3db5-42e2-a51e-27b8a767ced2">
<img width="765" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/9a29976f-8081-4469-ad96-1aeb6248d441">

**Comment by HenryXiaoYang** [comment]
windows环境我没测试过

docker启动会不会打错了

下面是正确的
```
#启动Docker
docker run --name xybotwechat \
    -e HOOK_PROC_NAME=WeChat \
    -e HOOK_DLL=auto.dll \
    -e TARGET_AUTO_RESTART="yes" \
    -e INJ_CONDITION="[ \"\`sudo netstat -tunlp | grep 5555\`\" != '' ] && exit 0 ; sleep 5 ; curl 'http://127.0.0.1:8680/hi' 2>/dev/null | grep -P 'code.:0'" \
    -e TARGET_CMD=wechat-start \
    -p 8080:8080 -p 5555:5555 -p 5900:5900 \
    --add-host=dldir1.qq.com:127.0.0.1 \
    chisbread/wechat-service:latest
```

**Comment by HenryXiaoYang** [comment]
windows可以不用docker，运行对应版本的微信然后注入hook，然后能直接运行XYBot了

微信3.6.0.18链接：https://github.com/tom-snow/wechat-windows-versions/releases?q=3.6.0.18
微信hook链接：https://github.com/ChisBread/wechat-service/blob/master/bin_deps/auto.dll
注入器：
[微信DLL注入器V1.0.3.exe.zip](https://github.com/HenryXiaoYang/XYBot/files/14075483/DLL.V1.0.3.exe.zip)

**Comment by YaoGGGG** [comment]
<img width="763" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/157867279/5b1e5d7a-bf37-4fcb-b548-2b98eaa6044d">
震惊，登上了！感谢（以及感谢其他人之前的贡献）！！！我接着配置！

**Comment by YaoGGGG** [comment]
没找到二维码捏，远程请您喝杯咖啡！
