### ISSUE TITLE
您好，为什么在启动docker镜像的时候会一直弹inject condition not pass

### ISSUE THREAD

**Issue by BTSRK** [HenryXiaoYang/XYBot#17]
按照教程启动docker镜像的时候会一直弹出 inject condition not pass 回显 ，应该是失败了吧？请问有解决方法吗？
[ERR.txt](https://github.com/HenryXiaoYang/XYBot/files/14076635/ERR.txt)

**Comment by HenryXiaoYang** [comment]
这是正常的，要登陆微信后才会注入hook，所以它会一直监测是否登陆。

你可以扫码登陆微信然后他就自动注入了。

**Comment by BTSRK** [comment]
好的，谢谢回复。还有一个问题，刚开始容器创建后，微信扫码界面是有的，后续我该如何调用出这个扫码登录界面？

**Comment by HenryXiaoYang** [comment]
进入vnc然后连接就可以登陆微信了

**Comment by BTSRK** [comment]
![image](https://github.com/HenryXiaoYang/XYBot/assets/108665025/e995b7d2-493c-44b1-8164-52816ba880f3)
vnc 登录显示的是这样子  没找到哪里打开微信的地方

**Comment by HenryXiaoYang** [comment]
重启docker再试试
