### ISSUE TITLE
用了两周发现的一些bug

### ISSUE THREAD

**Issue by notomatoes** [HenryXiaoYang/XYBot#2]
1. 有时候微信弹更新窗的时候会卡死，微信会掉出去，需要kill微信或者重启pod， 不知道能不能屏蔽掉提醒更新的弹窗
2. 查询积分没有针对群组隔离
3. 数据库没用户的时候第一次签到有概率没反应

**Comment by HenryXiaoYang** [comment]
> 1. 有时候微信弹更新窗的时候会卡死，微信会掉出去，需要kill微信或者重启pod， 不知道能不能屏蔽掉提醒更新的弹窗
> 2. 查询积分没有针对群组隔离
> 3. 数据库没用户的时候第一次签到有概率没反应

第一点：能否提供下卡死的描述？是Docker卡死还是就微信窗口卡死但其他东西（bash）还可以用？ 我这里没遇见过这种情况。可以试试在微信设置中把自动更新关掉。

第二点：积分没有隔离是因为怕用户在多个群聊中反复签到而刷取积分滥用ChatGPT。

第三点：我会尽快debug然后修复。

感谢提供反馈！

**Comment by HenryXiaoYang** [comment]
> 1. 有时候微信弹更新窗的时候会卡死，微信会掉出去，需要kill微信或者重启pod， 不知道能不能屏蔽掉提醒更新的弹窗
> 2. 查询积分没有针对群组隔离
> 3. 数据库没用户的时候第一次签到有概率没反应

第三点的bug在commit ad1c810已经修复了，我测试也没出现问题，请保留userpoints.db然后替换其他文件并更新config.yml

**Comment by HenryXiaoYang** [comment]
微信弹更新窗的时候点忽略本次更新，然后拖动下微信窗口就不会卡死了
