### ISSUE TITLE
启动问题卡死请教

### ISSUE THREAD

**Issue by PeterChen1997** [HenryXiaoYang/XYBot#21]
我在 2核2G 的云服务器上运行了 docker 直接卡死了..

**Comment by HenryXiaoYang** [comment]
可否发下docker日志

**Comment by PeterChen1997** [comment]
![image](https://github.com/HenryXiaoYang/XYBot/assets/21072589/4817c8aa-dfb0-459e-b5be-a6b4e1cf4b1f)

日志看上去好像没问题🤔

**Comment by PeterChen1997** [comment]
开跑以后，直接服务器卡死了 重启就好了，老哥速度真快，可以考虑整一个 discord 或者 tg，感谢分享代码

**Comment by PeterChen1997** [comment]
然后老哥还有个问题，这个 vnc 的端口代码里好像是 8080 了，文档还没改，还是 4000

**Comment by PeterChen1997** [comment]
并且发现 2核2G 确实跑步太了.. 一分钟又卡死了，可能还是得 4G
![image](https://github.com/HenryXiaoYang/XYBot/assets/21072589/1a0cb331-d27f-4729-8ef4-5071241cb8c8)

**Comment by HenryXiaoYang** [comment]
是滴，最耗资源的是微信本身，这一点我没办法。

文档我尽快修改

**Comment by PeterChen1997** [comment]
好咧👍

**Comment by PeterChen1997** [comment]
想请问下大佬，这种 dll 方式，有 ts 的实现方案吗

**Comment by HenryXiaoYang** [comment]
请问ts是什么东西

**Comment by PeterChen1997** [comment]
typescript 🤣

**Comment by PeterChen1997** [comment]
因为目前没法跑在云服务器上，打算本地跑，这样的话，逻辑都只能写在本地.. python 确实不太熟悉哈哈哈

**Comment by HenryXiaoYang** [comment]
本地是可以跑的可以看这个issue：https://github.com/HenryXiaoYang/XYBot/issues/16#issuecomment-1913528350
