### ISSUE TITLE
连接vnc以后，没有微信

### ISSUE THREAD

**Issue by zadishu** [HenryXiaoYang/XYBot#24]
启动日志
![微信图片_20240228114652](https://github.com/HenryXiaoYang/XYBot/assets/110985414/ff16718c-891e-477e-ad38-0f08d89a7040)

**Comment by HenryXiaoYang** [comment]
在vnc中打开bash，```top```一下看看微信是否在运行

**Comment by zadishu** [comment]
![Uploading 微信截图_20240304155714.png…]()

**Comment by zadishu** [comment]
![微信截图_20240304155714](https://github.com/HenryXiaoYang/XYBot/assets/110985414/731f5997-7bec-4eca-b217-f5aa9a28c099)

**Comment by HenryXiaoYang** [comment]
尝试重启容器或者重新拉取docker image

**Comment by zadishu** [comment]
尝试多次重启，和多次拉取，结果都是一样

**Comment by HenryXiaoYang** [comment]
你是在什么设备什么操作系统上部署的

**Comment by zadishu** [comment]
openwrt上的docker

**Comment by HenryXiaoYang** [comment]
不知道这个内核是否支持这个镜像，这个镜像用了wine，对环境要求挺高的
