### ISSUE TITLE
卡在31% 是不是版本太低了

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [HenryXiaoYang/XYBot#25]
![image](https://github.com/HenryXiaoYang/XYBot/assets/8020726/145e0a49-7bdd-4307-a67f-17040a0c2bf1)

**Comment by HangJau** [comment]
我也遇到了这个问题，看注入日志也没啥报错
![屏幕截图 2024-03-02 102324](https://github.com/HenryXiaoYang/XYBot/assets/48112437/3f922d67-973d-4e00-adde-d4e7cbb873f7)
![屏幕截图 2024-03-02 102428](https://github.com/HenryXiaoYang/XYBot/assets/48112437/0322a66e-8b02-477a-9073-8fd9d6db2edb)

**Comment by HenryXiaoYang** [comment]
docker run时不要用挂载，微信设置文件目录时自己新建一个文件夹以防止权限问题

**Comment by HangJau** [comment]
> docker run时不要用挂载，微信设置文件目录时自己新建一个文件夹以防止权限问题

没加挂载呀  直接用的这个命令启动的
docker run --name xybotwechat \
    -e HOOK_PROC_NAME=WeChat \
    -e HOOK_DLL=auto.dll \
    -e TARGET_AUTO_RESTART="yes" \
    -e INJ_CONDITION="[ \"\`sudo netstat -tunlp | grep 5555\`\" != '' ] && exit 0 ; sleep 5 ; curl 'http://127.0.0.1:8680/hi' 2>/dev/null | grep -P 'code.:0'" \
    -e TARGET_CMD=wechat-start \
    -p 4000:8080 -p 5555:5555 -p 5900:5900 \
    --add-host=dldir1.qq.com:127.0.0.1 \
    chisbread/wechat-service:latest

**Comment by liuhuapiaoyuan** [comment]
我也没有挂。。。。

**Comment by HenryXiaoYang** [comment]
第一次打开微信应该有设置文件目录的

不要用默认的，默认的有权限问题

自己创建一个新文件夹

**Comment by HangJau** [comment]
> 第一次打开微信应该有设置文件目录的
> 
> 不要用默认的，默认的有权限问题
> 
> 自己创建一个新文件夹

第一次打开微信没看到文件目录设置，目前换用root用户启动就没问题了。。 感觉这块可以在文档里面描述下，启动直接用root用户吧

**Comment by HangJau** [comment]
> 我也没有挂。。。。

用root用户启动容器试试我这边使用root启动已经可以了

**Comment by liuhuapiaoyuan** [comment]
👌

**Comment by liuhuapiaoyuan** [comment]
为啥还是不行。。。用了root权限 ，手动调WechatFiles的权限 都没用

**Comment by HangJau** [comment]
> 为啥还是不行。。。用了root权限 ，手动调WechatFiles的权限 都没用

你这个情况没遇到了额，我是在主机上用root直接启动docker  然后扫码就加载出微信页面了。机器人 发消息这些都是OK的 发送文件还没试过。 再试试呢

**Comment by HenryXiaoYang** [comment]
不排除是微信本身问题，试一下微信是否能在本地电脑上登录
