### ISSUE TITLE
连接之后，没有微信，然后直接报错了

### ISSUE THREAD

**Issue by pigKinger** [HenryXiaoYang/XYBot#26]
<img width="1431" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/50476515/d8f224e1-0784-46b0-a369-18a0ced63d9d">

**Comment by pigKinger** [comment]
<img width="567" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/50476515/2f7839d6-93f4-45e9-8934-1c4a87f8ee88">

**Comment by pigKinger** [comment]
<img width="489" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/50476515/ba614546-55ad-420a-83c9-8e1c6b13805d">
docker日志

**Comment by pigKinger** [comment]
<img width="1381" alt="image" src="https://github.com/HenryXiaoYang/XYBot/assets/50476515/03c73e4b-9ce9-4ded-9548-126538184759">

**Comment by HenryXiaoYang** [comment]
系统问题，有些系统如centos内核版本过低，建议换成内核版本高一点的系统
