### ISSUE TITLE
群二维码可以重新发下吗

### ISSUE THREAD

**Issue by w32x42y** [HenryXiaoYang/XYBot#27]
过期了，谢谢

**Comment by HenryXiaoYang** [comment]
请查看dev分支中的readme

**Comment by w32x42y** [comment]
> 请查看dev分支中的readme

一样的是过期的二维码，3月30日到期了

**Comment by HenryXiaoYang** [comment]
![xybotchatgroup](https://github.com/HenryXiaoYang/XYBot/assets/83214045/08d1b3ce-43e4-471b-a058-72d3f3d6fb5c)
