### ISSUE TITLE
不能使用GPT，检查配置都正常

### ISSUE THREAD

**Issue by hanjinggang** [HenryXiaoYang/XYBot#28]
使用GPT时提示错误，出现错误，已补回积分！⚠️(False, NotFoundError("Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}"))

**Comment by HenryXiaoYang** [comment]
v0.0.5是有bug的 请使用dev分之中的v0.0.6
