### ISSUE TITLE
拉取不到Docker镜像，是不是0.0.6版本还没有上传

### ISSUE THREAD

**Issue by AnCool-OvO** [HenryXiaoYang/XYBot#34]
@HenryXiaoYang

**Comment by HenryXiaoYang** [comment]
<img width="923" alt="截屏2024-04-28 上午10 32 13" src="https://github.com/HenryXiaoYang/XYBot/assets/83214045/22f3c387-e234-44b3-ba74-6a6b9841d0d6">

拉取得到啊

**Comment by AnCool-OvO** [comment]
> <img alt="截屏2024-04-28 上午10 32 13" width="923" src="https://private-user-images.githubusercontent.com/83214045/326224778-22f3c387-e234-44b3-ba74-6a6b9841d0d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzI1OTgsIm5iZiI6MTcxNDI3MjI5OCwicGF0aCI6Ii84MzIxNDA0NS8zMjYyMjQ3NzgtMjJmM2MzODctZTIzNC00NGIzLWJhNzQtNmE2Yjk4NDFkMGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAyNDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZGM2OGU4YWMyYTE4N2YwZjk5MmZiNmQxNmFkM2YxZjdjNGY1NWRjMzdjMjczOWIzMTUxYTE0YjUyYWFkMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3z3eBaOiNoWH_aAdD2bzmbhOgZZMEYw3xuDmdZVsWc">
> 拉取得到啊


好的不好意思，我不知道后面要改掉换成版本号，是个新手
