### ISSUE TITLE
被封了

### ISSUE THREAD

**Issue by tensor-tech** [HenryXiaoYang/XYBot#44]
华为云 windows server 最新代码
![image](https://github.com/HenryXiaoYang/XYBot/assets/30520357/e45a248e-deba-4e50-b1f8-721278a1b8cf)

**Comment by HenryXiaoYang** [comment]
新的号开机器人不管怎么样都一定封的，要养一段时间的号

**Comment by tensor-tech** [comment]
是老账号，我用了六年

**Comment by tensor-tech** [comment]
我重新登录之后，就被封了

**Comment by HenryXiaoYang** [comment]
请问是异地服务器登陆还是本地电脑登陆，是否有其他版本的微信安装着？

**Comment by tensor-tech** [comment]
我说一下我的操作，我安装windows 教程搭建了一遍，登录上去，测试没有问题，然后我换了一个账号测试，重启一下python程序，重新注入，两个账号都是3年以上的老账号，两个账号同时被封。

新服务器，没有其他版本微信，异地登录，服务器在上海，我不在上海。

**Comment by viper2383** [comment]
我的发，不敢装了

**Comment by HenryXiaoYang** [comment]
异地登录的风险是更大，毕竟检测出是异地很容易

**Comment by hedada-hc** [comment]
这种hook的被封是非常容易的，还是我开发的那种非注入 非hook的比较适合企业
