### ISSUE TITLE
运行下载的微信低版本提示修复 wechat_launcher_bypass_ver_check.exe 运行失败

### ISSUE THREAD

**Issue by koala9527** [HenryXiaoYang/XYBot#45]
如图所示：
此应用无法在你的电脑上运行
着要规到适用于你的电脑的版本，请咨询软件发布者

![bcd935e0551405eb62f3e741d23d1a6](https://github.com/HenryXiaoYang/XYBot/assets/36888009/b360d3f2-95fb-4d81-b669-7f5415fff375)

设备信息：
设备名称	N100
处理器	Intel(R) N100   800 MHz
机带 RAM	8.00 GB (7.75 GB 可用)
设备 ID	35FF02D0-XXXXX-XXXXX-XXXXX-XXXXXXXXXXXXXXX
产品 ID	00329-XXXXX-XXXXX-XXXXX
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 11 企业版
版本	23H2
安装日期	‎2024/‎2/‎27
操作系统版本	22631.3593
体验	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by HenryXiaoYang** [comment]
尝试设置一下防火墙，这个问题网上回答蛮多的，可以自行搜索下

**Comment by koala9527** [comment]
> 尝试设置一下防火墙，这个问题网上回答蛮多的，可以自行搜索下

我试试

**Comment by HenryXiaoYang** [comment]
请尝试新的版本
