### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by tianpeng199712** [HenryXiaoYang/XYBot#48]
只有输入/菜单 成功，其余它提示报错；；；群二维码已失效啊

**Comment by HenryXiaoYang** [comment]
发下日志

**Comment by tianpeng199712** [comment]
耽误大佬时间帮忙看一下






风向决定发型
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HenryXiaoYang/XYBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月10日(星期一) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HenryXiaoYang/XYBot] 使用方法 (Issue #48)





 
发下日志

**Comment by HenryXiaoYang** [comment]
额日志呢？

**Comment by tianpeng199712** [comment]
日志收到了吗



---原始邮件---
发件人: "Henry ***@***.***&gt;
发送时间: 2024年6月10日(周一) 晚上10:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HenryXiaoYang/XYBot] 使用方法 (Issue #48)




 
额日志呢？

**Comment by HenryXiaoYang** [comment]
我这里没有看到

**Comment by tianpeng199712** [comment]
哥，那你微信多少我加您，或者您加我呢，1799413885



---原始邮件---
发件人: "Henry ***@***.***&gt;
发送时间: 2024年6月12日(周三) 晚上10:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HenryXiaoYang/XYBot] 使用方法 (Issue #48)




 
我这里没有看到

**Comment by HenryXiaoYang** [comment]
日志文件发我邮箱吧 henryyang666@hotmail.com

**Comment by HenryXiaoYang** [comment]
微信退出登录了吧，重启机器人重新登陆

**Comment by HenryXiaoYang** [comment]
然后天气是要设置api密钥的，在配置文件里
新闻报错是因为XYBot用的新闻api格式又变了，我这几天很忙，还没来得及修

**Comment by tianpeng199712** [comment]
目前是没登录状态，这是之前那天的日志，就是发/菜单正常，



---原始邮件---
发件人: "Henry ***@***.***&gt;
发送时间: 2024年6月13日(周四) 晚上7:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HenryXiaoYang/XYBot] 使用方法 (Issue #48)




 
微信退出登录了吧

**Comment by HenryXiaoYang** [comment]
1.1 获取天气
1.3 ChatGPT

这2个功能都需要设置密钥的，配置文件都在XYBot/plugins里

**Comment by tianpeng199712** [comment]
我有添加天气的api，按照正常格式复制粘贴进去的&nbsp;&nbsp;



---原始邮件---
发件人: "Henry ***@***.***&gt;
发送时间: 2024年6月13日(周四) 晚上7:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HenryXiaoYang/XYBot] 使用方法 (Issue #48)




 
然后天气是要设置api密钥的，在配置文件里
 新闻报错是因为XYBot用的新闻api格式又变了，我这几天很忙，还没来得及修

**Comment by HenryXiaoYang** [comment]
http状态码是401，api密钥有误吧

**Comment by tianpeng199712** [comment]
我回去检查下api配置



---原始邮件---
发件人: "Henry ***@***.***&gt;
发送时间: 2024年6月13日(周四) 晚上7:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HenryXiaoYang/XYBot] 使用方法 (Issue #48)




 
http状态码是401，api密钥有误吧
