### ISSUE TITLE
五子棋指令打不开，没有报错但是没有反应

### ISSUE THREAD

**Issue by xiaochenchui** [HenryXiaoYang/XYBot#53]
五子棋指令打不开，没有报错但是没有反应，另外我想用微信小号做机器人，但是只有一个手机设备，退出登录小号也会退，有没有什么办法不让他退出呢

**Comment by xiaochenchui** [comment]
顺便求一个交流群邀请，二维码过期了

**Comment by HenryXiaoYang** [comment]
发下日志文件。只有一个手机设备可以多开微信

**Comment by Sendu-sanxing** [comment]
> 五子棋指令打不开，没有报错但是没有反应，另外我想用微信小号做机器人，但是只有一个手机设备，退出登录小号也会退，有没有什么办法不让他退出呢

”退出登录小号也会退“，想要退出登录电脑小号不退，只要在手机退出登录时，不要联网就可以了。

**Comment by HenryXiaoYang** [comment]
stale issue
