### ISSUE TITLE
提示机器人账号未登录，请使用浏览器访问127.0.0.1:4000/vnc.html

### ISSUE THREAD

**Issue by LILUOX** [HenryXiaoYang/XYBot#54]
如题，我客户端微信登录的了。
然后我打开127.0.0.1:4000/vnc.html 这个网页显示 不可访问。按照网上教程配置了之后127.0.0.1 可以访问了，但是vnc 还是不行。

**Comment by HenryXiaoYang** [comment]
在本地运行的还是在docker上运行的

**Comment by HenryXiaoYang** [comment]
然后就是可尝试下新的版本，部署方便了很多

**Comment by LILUOX** [comment]
在本地运行的

**Comment by HenryXiaoYang** [comment]
pull下新版本吧 看下现在的部署文档
