### ISSUE TITLE
长时间运行导致的内存泄露

### ISSUE THREAD

**Issue by HenryXiaoYang** [HenryXiaoYang/XYBot#7]
长时间运行会导致内存泄露，最后触发linux的内存保护把进程kill了
![67181701528456_ pic](https://github.com/HenryXiaoYang/XYBot/assets/83214045/24f6de7b-0888-4ebc-a722-87b162b4ff7c)

**Comment by J-Z-Z** [comment]
什么是内存， 为什么内存会泄漏？ 这个要从c++ 说起
内存泄漏（Memory Leak）是指程序中己动态分配的堆内存由于某种原因程序未释放或无法释放，造成系统内存的浪费，导致程序运行速度减慢甚至系统崩溃等严重后果。
new操作符或者free函数的时候，实际上是在堆上为其分配内存，这个内存指的是RAM，而不是硬盘等永久存储。持续申请而不释放(或者少量释放)内存的应用程序，最终因内存耗尽导致OOM(out of memory)。

去查查看， python 有没有分配内存， 释放内存？？

**Comment by HenryXiaoYang** [comment]
貌似优化后好了 待检查

**Comment by HenryXiaoYang** [comment]
已修复 问题是database.py单态有问题，每次用数据库就开个线程 从多线程更改为异步后修复了 0.0.5 pre 之前的都有问题
