### ISSUE TITLE
windows    Wcferry注入失败

### ISSUE THREAD

**Issue by Himhu** [HenryXiaoYang/XYBot#71]
'wcferry_helper' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2024-10-23 12:44:32.679 | ERROR    | __main__:main:81 - Wcferry注入失败

**Comment by sk1ye** [comment]
![image](https://github.com/user-attachments/assets/b99c2a3d-dc4e-43db-950b-404102528391)
一样的

**Comment by sk1ye** [comment]
![image](https://github.com/user-attachments/assets/f4b94537-696a-493e-8c25-067c580dab21)
可以加一个绝对路径，而不是相对路径，我的已成功

**Comment by Himhu** [comment]
> ![image](https://private-user-images.githubusercontent.com/162893982/379200359-f4b94537-696a-493e-8c25-067c580dab21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Nzk3MTYsIm5iZiI6MTcyOTY3OTQxNiwicGF0aCI6Ii8xNjI4OTM5ODIvMzc5MjAwMzU5LWY0Yjk0NTM3LTY5NmEtNDkzZS04YzI1LTA2N2M1ODBkYWIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxMDMwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTc5OGRkZDU2M2QyOTBjM2ZlZGUxODg2YWRhOGJjMWE0MWJiNzZmZTYwYzJiMmFiZjg0YmUzNzA1MzQ5MDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WRys_DwRnICPUr5SmbWQ-aP_IBfEXkW7uVK_cCtbO5M) 可以加一个绝对路径，而不是相对路径，我的已成功

明白了，感谢

**Comment by HenryXiaoYang** [comment]
请尝试新的代码
