### ISSUE TITLE
五子棋、ChatGpt等一些指令报错

### ISSUE THREAD

**Issue by Colwn** [HenryXiaoYang/XYBot#76]
输入五子棋报错没反应，控制台报错： list index out of range。
输入2.3、2.3 五子棋这些没反应，也没报错，输入五子棋 2.3 控制台报错 指令格式错误!| [发送到] 19035256431@chatroom
这俩我知道咋回事
输入ChatGpt报错 参数错误!| [发送到] 19035256431@chatroom
这个是不是我配置文件中的chatgpt的域名不对？域名我填的是：https://platform.openai.com/docs/api-reference/chat/create
日志贴上
[log_2024-10-30_17-17-13_143962.log](https://github.com/user-attachments/files/17569258/log_2024-10-30_17-17-13_143962.log)

**Comment by HenryXiaoYang** [comment]
指令错了
查询五子棋菜单是
菜单 2.3

你这个open ai的api base不对，你把openai的文档链接填进去当然报错了。

请仔细阅读文档！
