### ISSUE TITLE
vnc能否设置密码？

### ISSUE THREAD

**Issue by yuanwangz** [HenryXiaoYang/XYBot#8]
通过网页能直接连接vnc，能否设置密码提升安全性？

**Comment by HenryXiaoYang** [comment]
1. 在终端```docker ps``` 找出XYBot的容器的```CONTAINER ID```
2. 执行```docker exec -it (XYBot的容器的CONTAINER ID) /bin/sh```
3. 在容器内执行```x11vnc --storepasswd```
4. 然后跟着提示设置密码
5. 编辑这个文件```/etc/supervisord.d/x11vnc.conf```
6. 在第二行的```command=x11vnc -forever -shared```末尾加入```-rfbauth /home/app/.vnc/passwd```
最后应该是```command=x11vnc -forever -shared -rfbauth /home/app/.vnc/passwd```
7. ```exit```退出docker然后重启docker
8. 现在用网页连接vnc应该要输入密码
