### ISSUE TITLE
[BUG] 五子棋功能报错 list index out of range

### ISSUE THREAD

**Issue by xiaochenchui** [HenryXiaoYang/XYBot#90]
是用windows搭建的，其他功能都正常，就五子棋报错 list index out of range

![微信图片_20241128094644](https://github.com/user-attachments/assets/2d099d91-7cea-4fec-9d9f-d1cf5c96acd9)

**Comment by HenryXiaoYang** [comment]
ats列表是空的，这个消息中的@是复制粘贴的吧。手动打@试试

**Comment by xiaochenchui** [comment]
> ats列表是空的，这个消息中的@是复制粘贴的吧。手动打@试试

感谢回复，手打的确实可以，看来是不能用鼠标右键来@，不过我这里还遇到了一个问题，抢红包输对了验证码报了这个错
![1732778436537](https://github.com/user-attachments/assets/1f064ebd-7b3b-4011-9a6d-7d8594b7eab2)

**Comment by HenryXiaoYang** [comment]
> > ats列表是空的，这个消息中的@是复制粘贴的吧。手动打@试试
> 
> 感谢回复，手打的确实可以，看来是不能用鼠标右键来@，不过我这里还遇到了一个问题，抢红包输对了验证码报了这个错 ![1732778436537](https://private-user-images.githubusercontent.com/53653075/390680032-1f064ebd-7b3b-4011-9a6d-7d8594b7eab2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTE0MzgsIm5iZiI6MTczMjg1MTEzOCwicGF0aCI6Ii81MzY1MzA3NS8zOTA2ODAwMzItMWYwNjRlYmQtN2IzYi00MDExLTlhNmQtN2Q4NTk0YjdlYWIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAzMzIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwY2Q4YWI1N2I1ZmM0NDYwNzJjMTg0ZTVkNWVmMjg3OGI4YmQ0ODY1ZWJmNjVjMmE3ODA3MTU1ZWQzYTdkNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EPl_pqIyz7IFvqjEk_TWuOfw9naUKpN6BGd31F3G5GY)

收到收到
