### ISSUE TITLE
[BUG] 群已经加入黑名单，但是群@还是会回复

### ISSUE THREAD

**Issue by dongguarrr** [HenryXiaoYang/XYBot#97]
**请描述这个 Bug Describe the bug**
Bug的清晰简洁的描述。
群已经加入黑名单，但是群@还是会回复
**如何复现 To Reproduce**
重现该行为的步骤 Steps to reproduce the behavior:
1. 发送 "......" Send "..."
2. 点击 "......" Click "..."
3. 查看报错 See error

**预期行为 Expected behavior**
期望发生的事情。

**截屏 Screenshots**
如果可以的话，添加截图来帮助解释。
![image](https://github.com/user-attachments/assets/b5953993-1d74-4a5d-83c7-621cff3c3fa8)
![image](https://github.com/user-attachments/assets/fd89d847-e3ea-4f11-b06a-d7d3941a0a6e)

**运行环境 Operating environment**
 - OS: [e.g. Windows10, Windows11, In Docker]
 - Python版本 Python version: [e.g. 3.12, In Docker]
 - XYBot版本 XYBot version [e.g. 2.0.0]
 Windows11
**额外信息 Additional context**
有关该问题的任何其他信息。

**Comment by HenryXiaoYang** [comment]
屏蔽模式有没有设置？发一下完整的`main_config.yml`

**Comment by dongguarrr** [comment]
已解决，模式忘了填了……
