### ISSUE TITLE
[BUG] 2.2.1版本，私聊或者艾特机器人时，后台报错

### ISSUE THREAD

**Issue by magisk317** [HenryXiaoYang/XYBot#99]
**请描述这个 Bug Describe the bug**
Bug的清晰简洁的描述。

**如何复现 To Reproduce**
重现该行为的步骤 Steps to reproduce the behavior:
1. 私聊机器人，或者群里艾特机器人
2. 机器人不回复，并且后台报错

**预期行为 Expected behavior**
机器人回复，或者弹出报错提示

**截屏 Screenshots**
![image](https://github.com/user-attachments/assets/83252678-5d87-4a5b-b136-16bcda05af64)

```
2024-12-14 11:37:13.585 | ERROR    | __main__:callback:29 - AsyncClient.__init__() got an unexpected keyword argument 'proxies'
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<AsyncClient.aclose() done, defined at C:\Program Files\Python312\Lib\site-packages\httpx\_client.py:1978> exception=AttributeError("'AsyncHttpxClientWrapper' object has no attribute '_state'")>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\httpx\_client.py", line 1982, in aclose
    if self._state != ClientState.CLOSED:
       ^^^^^^^^^^^
AttributeError: 'AsyncHttpxClientWrapper' object has no attribute '_state'
```

**运行环境 Operating environment**
 - OS: [Windows11]
 - Python版本 Python version: [e.g. 3.12.7]
 - XYBot版本 XYBot version [e.g. 2.2.1]
 - 微信版本 ：3.9.10.27
![image](https://github.com/user-attachments/assets/1264939b-0d8b-4ec5-beb2-7dc47bf1768f)

**额外信息 Additional context**
有关该问题的任何其他信息。

**Comment by magisk317** [comment]
还有个信息就是，因为没开chatgpt，所以接入了其他ai，比如通义千问或者智谱清言，我把gpt的关键词置空或者改成其他关键词，把gpt的关键词用来触发其他模型，不知道是不是这个原因导致的

如果是的话，我应该怎么修改，才能私聊或者艾特的时候默认以其他模型聊天，目前单独触发没问题，比如自定义的关键词，只有私聊和艾特这两种场景会报错

**Comment by HenryXiaoYang** [comment]
私聊和@都是单独自己一个插件，不与指令互通的。所以，如果要换ai服务，指令、私聊、@的插件都得改。

**Comment by HenryXiaoYang** [comment]
这也是用指令调用gpt没问题，但是私聊和@会报错的原因

**Comment by magisk317** [comment]
> 私聊和@都是单独自己一个插件，不与指令互通的。所以，如果要换ai服务，指令、私聊、@的插件都得改。

好的，了解，回头研究研究
